### PR TITLE
Testing/001 jsondochandling

### PR DESCRIPTION
**Pull request by keerekeerweere**
first refactored and working version

### CODE REVIEW

**Comment by darrylb123** [comment]
Just noticed this. Looks very interesting.
Are you going to merge it back with a pull request?

BTW, I added expire_after directives to the auto configure.
I'm happy to wait until you are ready to merge before I make any other changes.

**Comment by keerekeerweere** [comment]
Hi, thanks for your interest. Was doing a PR towards another repo and launched this PR almost by mistake, that's why I closed it again :-)

If you're interested sure, I'll launch the PR taking the latest version into account.

FYI: will also include some other fixes that I encountered while making this code compatible with esphome and home assistant, since that's my goal.

**Comment by darrylb123** [comment]
I'm very interested in your work.
I would like to know what the fixes were, just out of interest.
I will test your repo later.
How would you like to handle my changes yesterday?
I could roll them back so your pr applies cleanly then add them again
manually.

Also, I don't seem to get any data from the line relay and inverter status,
even though the data structure etc seems the same as sbfspot which works
correctly.
I hadn't looked too hard though.

**Comment by darrylb123** [comment]
Cloned your repo.
Ran into a few issues, I assume mostly due to case sensitivity on linux (which I use).
I have almost no experience with platformio (other than to compile tasmota).
After fixing the case errors, I got this link error inside the expressif bluetooth library.
/home/xxxxxx/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pio/build/espwroom32/libe2e/libBluetoothSerial.a(BluetoothSerial.cpp.o):(.literal._ZL8_stop_btv+0x18): undefined reference to `esp_spp_disconnect'

**Comment by darrylb123** [comment]
$ git diff
diff --git a/src/ESP32_SMA_Inverter_App.cpp b/src/ESP32_SMA_Inverter_App.cpp
index 33682e6..383048b 100644
--- a/src/ESP32_SMA_Inverter_App.cpp
+++ b/src/ESP32_SMA_Inverter_App.cpp
@@ -214,7 +214,7 @@ void ESP32_SMA_Inverter_App::loadConfiguration() {
     appConfig.scanRate = doc["scanRate"] | 60 ;
     appConfig.hassDisc = doc["hassDisc"] | true ;
     appConfig.timezone = doc["timezone"] | "";
-    appConfig.ntpHostname = doc["ntphostname"] | "";
+    appConfig.ntphostname = doc["ntphostname"] | "";
   #endif
 
   
diff --git a/src/SMA_Inverter.cpp b/src/SMA_Inverter.cpp
index f9b94f5..d3a9a5d 100644
--- a/src/SMA_Inverter.cpp
+++ b/src/SMA_Inverter.cpp
@@ -24,7 +24,7 @@ SOFTWARE.
 
 #include <Arduino.h>
 #include "SMA_Inverter.h"
-#include "SMA_utils.h"
+#include "SMA_Utils.h"
 #include "BluetoothSerial.h"
 #include "ESP32_SMA_Inverter_App.h"
 
(END)
+++ b/src/ESP32_SMA_Inverter_App.cpp
@@ -214,7 +214,7 @@ void ESP32_SMA_Inverter_App::loadConfiguration() {
     appConfig.scanRate = doc["scanRate"] | 60 ;
     appConfig.hassDisc = doc["hassDisc"] | true ;
     appConfig.timezone = doc["timezone"] | "";
-    appConfig.ntpHostname = doc["ntphostname"] | "";
+    appConfig.ntphostname = doc["ntphostname"] | "";
   #endif
 
   
diff --git a/src/SMA_Inverter.cpp b/src/SMA_Inverter.cpp
index f9b94f5..d3a9a5d 100644
--- a/src/SMA_Inverter.cpp
+++ b/src/SMA_Inverter.cpp
@@ -24,7 +24,7 @@ SOFTWARE.
 
 #include <Arduino.h>
 #include "SMA_Inverter.h"
-#include "SMA_utils.h"
+#include "SMA_Utils.h"
 #include "BluetoothSerial.h"
 #include "ESP32_SMA_Inverter_App.h"

**Comment by keerekeerweere** [comment]
yes indeed, did some work on a branch here to finalize.
I'll get back to you for an update and provide a version that's ok.

As for the plan of action. Let's get back to your initial version with the expire_after and work from that. I'll re-play the changes on a version that contains that modification and see how far I can get.

**Comment by darrylb123** [comment]
Ok, the changes a pretty straight forward.

**Comment by darrylb123** [comment]
How are you going with it?
I went to have a look at your progress and the repo is gone.

**Comment by keerekeerweere** [comment]
indeed, had some merge issues for the pull request. 
So I recreated the clone of the repo and now you should have a compiling version. haven't tested it yet.
[https://github.com/keerekeerweere/ESP32_SMA-Inverter-MQTT](https://github.com/keerekeerweere/ESP32_SMA-Inverter-MQTT)

FYI: also succeeded in creating a esphome compatible version, meaning it can be configured and deployed directly from homeassistants' esphome plugin. but that's another story. some issues remain there too.
[https://github.com/keerekeerweere/esphome_smabluetooth](https://github.com/keerekeerweere/esphome_smabluetooth)

**Comment by keerekeerweere** [comment]
fwiw, _"Also, I don't seem to get any data from the line relay and inverter status,"_
this is fixed in the esphome version, with 'translated return codes and such". Haven't had a chance to backport this into the fresh fork of this repo

**Comment by darrylb123** [comment]
Just cloned your fork and tried a compile. I use Linux and tripped over a filename case.
-#include "SMA_utils.h"
+#include "SMA_Utils.h"

Won't link though. I'm not at all familiar with platformio and I'm not sure whether it's getting the correct library version??
libBluetoothSerial.a(BluetoothSerial.cpp.o):(.literal._ZL8_stop_btv+0x18): undefined reference to `esp_spp_disconnect'

**Comment by keerekeerweere** [comment]
ok, fixed the SMA_utils case thing.
I believe platform.io is using this version of the BluetoothSerial 
https://github.com/espressif/arduino-esp32/tree/master/libraries/BluetoothSerial

if you want to try platform.io, just use vscode and add the platform.io plugin, the platformio.ini file should take care of the rest.
I recently also used clion (much better a c++ coding and refactoring than vscode but a less intuitive on the platformio usage)

here is my vscode build output: 
`Processing espwroom32 (platform: espressif32; board: lolin_d32; framework: arduino)

CONFIGURATION: https://docs.platformio.org/page/boards/espressif32/lolin_d32.html
PLATFORM: Espressif 32 (6.3.2) > WEMOS LOLIN D32
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
DEBUG: Current (cmsis-dap) External (cmsis-dap, esp-bridge, esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)
PACKAGES:
 - framework-arduinoespressif32 @ 3.20009.0 (2.0.9)
 - tool-esptoolpy @ 1.40501.0 (4.5.1)
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch5
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 36 compatible libraries
Scanning dependencies...
Dependency Graph
|-- ArduinoJson @ 6.21.3
|-- PubSubClient @ 2.8.0
|-- ESP32 logger @ 1.0.3+sha.224251f
|-- WebServer @ 2.0.0
|-- WiFi @ 2.0.0
|-- BluetoothSerial @ 2.0.0
|-- FS @ 2.0.0
|-- LittleFS @ 2.0.0
|-- Preferences @ 2.0.0
Building in release mode
Compiling .pio\build\espwroom32\src\ESP32_SMA-Inverter-MQTT.cpp.o
Compiling .pio\build\espwroom32\src\ESP32_SMA_MQTT.cpp.o
Compiling .pio\build\espwroom32\src\SMA_Inverter.cpp.o
Linking .pio\build\espwroom32\firmware.elf
Retrieving maximum program size .pio\build\espwroom32\firmware.elf
Checking size .pio\build\espwroom32\firmware.elf
Advanced Memory Usage is available via "PlatformIO Home > Project Inspect"
RAM:   [==        ]  20.0% (used 65508 bytes from 327680 bytes)
Flash: [========  ]  82.6% (used 1624881 bytes from 1966080 bytes)
Building .pio\build\espwroom32\firmware.bin
esptool.py v4.5.1
Creating esp32 image...
Merged 25 ELF sections
Successfully created esp32 image.`

**Comment by darrylb123** [comment]
Found that if I remove my old platformio install and pulled a new set, the link errors went away.
I started with a wiped esp32 and no wifi credentials in Config.h as i usually use ESPTouch to set the wifi login.
I found I had to include the Wifi.Begin test logic inside the #ifdef
#ifdef WIFI_SSID
  //overriding ssid and hostname
  logD("wifi begin with ssid(%s) and password (.......)", WIFI_SSID);
  WiFi.begin(WIFI_SSID, WIFI_PASSWORD);
  for  (int w=0; w<=10 || WiFi.status() != WL_CONNECTED; w++) {
    delay(500);
    logD(".wifi.");
  }
#else
  WiFi.begin();
#endif
  logD("Using config");

**Comment by keerekeerweere** [comment]
changed to an intermediate version. compiles and has most of the fixes and doesn't crash any more.

2023-08-14 17:45:46.0930 I ESP32_SMA_MQTT  { "Serial": 2100xxxxx1, "BTStrength":  70.98, "Uac": [ 237.90,   0.00,   0.00 ], "Iac": [   0.59,   0.00,   0.00 ], "Pac":   0.14, "Udc": [ 260.59 ,   0.00 ], "Idc": [   0.58 ,   0.00 ], "Wdc": [  0.15 ,   0.00 ], "Freq": 49.96, "EToday":  10.79, "ETotal":        24227.27, "InvTemp": 56.70, "DevStatus": 307, "GridRelay": 51 }

**Comment by darrylb123** [comment]
Looking good. I went looking for the timezone code as the time was wrong for me (+10).
You're obviously thinking about it. Were you thinking about Australia/Brisbane or +10

**Comment by darrylb123** [comment]
Also, now that I'm getting meaningful data for GridRelay and Device Status. I checked SBFSpot and saw the lookup into the TAGDefsxx.h.
Mine was returning 51 (Closed) for the grid relay and 307 (Ok) for device status. Should we just grab the most common tags from the list to return something useful??

**Comment by keerekeerweere** [comment]
Yes the rename of the codes into text is something interesting. I have done it on the esphome repo already. Might add that later on here too.
Things seem to be working quite good now. change the hass autodiscovery and state topics quite somewhat to get them more clearly. Had some issues inside home assistant but it was due to the missing device configuration in the auto discovery topics, also fixed now.
image

**Comment by keerekeerweere** [comment]
we should consider merging perhaps into a single repo ?

**Comment by darrylb123** [comment]
Yes. How do you want to do it?

**Comment by darrylb123** [comment]
I found and fixed a bug in the web configuration page when displaying the current AC V and A.
I'll wait until we decide what we're doing with the single repo before applying.
Here it is though:
@@ -273,16 +273,16 @@ table, th, td {\
   snprintf(tempstr, sizeof(tempstr),
 "<tr><td>MQTT Topic</td><td>%s</td></tr>\n\
  <tr><td>BT Signal Strength</td><td>%4.1f %</td></tr>\n\
-  <tr><td>Uac</td><td>%15.1f V</td></tr>\n\
- <tr><td>Iac</td><td>%15.1f A</td></tr>\n\
- <tr><td>Pac</td><td>%15.1f kW</td></tr>\n\
+  <tr><td>Uac</td><td>A: %15.1f ,B: %15.1f ,C: %15.1f V</td></tr>\n\
+ <tr><td>Iac</td><td>A: %15.1f ,B: %15.1f ,C: %15.1f A</td></tr>\n\
+ <tr><td>Pac</td><td>%15.2f kW</td></tr>\n\
  <tr><td>Udc</td><td>String 1: %15.1f V, String 2: %15.1f V</td></tr>\n\
  <tr><td>Idc</td><td>String 1: %15.1f A, String 2: %15.1f A</td></tr>\n\
  <tr><td>Wdc</td><td>String 1: %15.1f kW, String 2: %15.1f kW</td></tr>\n"
  , fulltopic
  , dispData.BTSigStrength
- , dispData.Uac
- , dispData.Iac
+ , dispData.Uac[0], dispData.Uac[1], dispData.Uac[2]
+ , dispData.Iac[0], dispData.Iac[1], dispData.Iac[2]
  , dispData.Pac
  , dispData.Udc[0], dispData.Udc[1]
  , dispData.Idc[0], dispData.Idc[1]

**Comment by darrylb123** [comment]
Are you going to submit a pull request? I'd like to make a change to the HA auto configuration code.

**Comment by keerekeerweere** [comment]
Hi, 
just submitted the pull request. 
FYI: HA auto discovery already works on the version of the pull request :-)

**Comment by darrylb123** [comment]
Yes, but I need to add device type so the kWh ends up in the energy tab.

**Pull request closed without merging**
